export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: 'AD', name: 'Andorra', flag: '🇦🇩' },
  { code: 'AE', name: 'Emirados Árabes Unidos', flag: '🇦🇪' },
  { code: 'AF', name: 'Afeganistão', flag: '🇦🇫' },
  { code: 'AG', name: 'Antígua e Barbuda', flag: '🇦🇬' },
  { code: 'AI', name: 'Anguilla', flag: '🇦🇮' },
  { code: 'AL', name: 'Albânia', flag: '🇦🇱' },
  { code: 'AM', name: 'Armênia', flag: '🇦🇲' },
  { code: 'AO', name: 'Angola', flag: '🇦🇴' },
  { code: 'AQ', name: 'Antártida', flag: '🇦🇶' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'AS', name: 'Samoa Americana', flag: '🇦🇸' },
  { code: 'AT', name: 'Áustria', flag: '🇦🇹' },
  { code: 'AU', name: 'Austrália', flag: '🇦🇺' },
  { code: 'AW', name: 'Aruba', flag: '🇦🇼' },
  { code: 'AX', name: 'Ilhas Åland', flag: '🇦🇽' },
  { code: 'AZ', name: 'Azerbaijão', flag: '🇦🇿' },
  { code: 'BA', name: 'Bósnia e Herzegovina', flag: '🇧🇦' },
  { code: 'BB', name: 'Barbados', flag: '🇧🇧' },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'BE', name: 'Bélgica', flag: '🇧🇪' },
  { code: 'BF', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BG', name: 'Bulgária', flag: '🇧🇬' },
  { code: 'BH', name: 'Bahrein', flag: '🇧🇭' },
  { code: 'BI', name: 'Burundi', flag: '🇧🇮' },
  { code: 'BJ', name: 'Benin', flag: '🇧🇯' },
  { code: 'BL', name: 'São Bartolomeu', flag: '🇧🇱' },
  { code: 'BM', name: 'Bermudas', flag: '🇧🇲' },
  { code: 'BN', name: 'Brunei', flag: '🇧🇳' },
  { code: 'BO', name: 'Bolívia', flag: '🇧🇴' },
  { code: 'BQ', name: 'Bonaire, Sint Eustatius e Saba', flag: '🇧🇶' },
  { code: 'BR', name: 'Brasil', flag: '🇧🇷' },
  { code: 'BS', name: 'Bahamas', flag: '🇧🇸' },
  { code: 'BT', name: 'Butão', flag: '🇧🇹' },
  { code: 'BV', name: 'Ilha Bouvet', flag: '🇧🇻' },
  { code: 'BW', name: 'Botsuana', flag: '🇧🇼' },
  { code: 'BY', name: 'Bielorrússia', flag: '🇧🇾' },
  { code: 'BZ', name: 'Belize', flag: '🇧🇿' },
  { code: 'CA', name: 'Canadá', flag: '🇨🇦' },
  { code: 'CC', name: 'Ilhas Cocos', flag: '🇨🇨' },
  { code: 'CD', name: 'República Democrática do Congo', flag: '🇨🇩' },
  { code: 'CF', name: 'República Centro-Africana', flag: '🇨🇫' },
  { code: 'CG', name: 'Congo', flag: '🇨🇬' },
  { code: 'CH', name: 'Suíça', flag: '🇨🇭' },
  { code: 'CI', name: 'Costa do Marfim', flag: '🇨🇮' },
  { code: 'CK', name: 'Ilhas Cook', flag: '🇨🇰' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'CM', name: 'Camarões', flag: '🇨🇲' },
  { code: 'CN', name: 'China', flag: '🇨🇳' },
  { code: 'CO', name: 'Colômbia', flag: '🇨🇴' },
  { code: 'CR', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CU', name: 'Cuba', flag: '🇨🇺' },
  { code: 'CV', name: 'Cabo Verde', flag: '🇨🇻' },
  { code: 'CW', name: 'Curaçao', flag: '🇨🇼' },
  { code: 'CX', name: 'Ilha Christmas', flag: '🇨🇽' },
  { code: 'CY', name: 'Chipre', flag: '🇨🇾' },
  { code: 'CZ', name: 'República Tcheca', flag: '🇨🇿' },
  { code: 'DE', name: 'Alemanha', flag: '🇩🇪' },
  { code: 'DJ', name: 'Djibuti', flag: '🇩🇯' },
  { code: 'DK', name: 'Dinamarca', flag: '🇩🇰' },
  { code: 'DM', name: 'Dominica', flag: '🇩🇲' },
  { code: 'DO', name: 'República Dominicana', flag: '🇩🇴' },
  { code: 'DZ', name: 'Argélia', flag: '🇩🇿' },
  { code: 'EC', name: 'Equador', flag: '🇪🇨' },
  { code: 'EE', name: 'Estônia', flag: '🇪🇪' },
  { code: 'EG', name: 'Egito', flag: '🇪🇬' },
  { code: 'EH', name: 'Saara Ocidental', flag: '🇪🇭' },
  { code: 'ER', name: 'Eritreia', flag: '🇪🇷' },
  { code: 'ES', name: 'Espanha', flag: '🇪🇸' },
  { code: 'ET', name: 'Etiópia', flag: '🇪🇹' },
  { code: 'FI', name: 'Finlândia', flag: '🇫🇮' },
  { code: 'FJ', name: 'Fiji', flag: '🇫🇯' },
  { code: 'FK', name: 'Ilhas Malvinas', flag: '🇫🇰' },
  { code: 'FM', name: 'Micronésia', flag: '🇫🇲' },
  { code: 'FO', name: 'Ilhas Faroé', flag: '🇫🇴' },
  { code: 'FR', name: 'França', flag: '🇫🇷' },
  { code: 'GA', name: 'Gabão', flag: '🇬🇦' },
  { code: 'GB', name: 'Reino Unido', flag: '🇬🇧' },
  { code: 'GD', name: 'Granada', flag: '🇬🇩' },
  { code: 'GE', name: 'Geórgia', flag: '🇬🇪' },
  { code: 'GF', name: 'Guiana Francesa', flag: '🇬🇫' },
  { code: 'GG', name: 'Guernsey', flag: '🇬🇬' },
  { code: 'GH', name: 'Gana', flag: '🇬🇭' },
  { code: 'GI', name: 'Gibraltar', flag: '🇬🇮' },
  { code: 'GL', name: 'Groenlândia', flag: '🇬🇱' },
  { code: 'GM', name: 'Gâmbia', flag: '🇬🇲' },
  { code: 'GN', name: 'Guiné', flag: '🇬🇳' },
  { code: 'GP', name: 'Guadalupe', flag: '🇬🇵' },
  { code: 'GQ', name: 'Guiné Equatorial', flag: '🇬🇶' },
  { code: 'GR', name: 'Grécia', flag: '🇬🇷' },
  { code: 'GS', name: 'Geórgia do Sul e Ilhas Sandwich do Sul', flag: '🇬🇸' },
  { code: 'GT', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'GU', name: 'Guam', flag: '🇬🇺' },
  { code: 'GW', name: 'Guiné-Bissau', flag: '🇬🇼' },
  { code: 'GY', name: 'Guiana', flag: '🇬🇾' },
  { code: 'HK', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'HM', name: 'Ilha Heard e Ilhas McDonald', flag: '🇭🇲' },
  { code: 'HN', name: 'Honduras', flag: '🇭🇳' },
  { code: 'HR', name: 'Croácia', flag: '🇭🇷' },
  { code: 'HT', name: 'Haiti', flag: '🇭🇹' },
  { code: 'HU', name: 'Hungria', flag: '🇭🇺' },
  { code: 'ID', name: 'Indonésia', flag: '🇮🇩' },
  { code: 'IE', name: 'Irlanda', flag: '🇮🇪' },
  { code: 'IL', name: 'Israel', flag: '🇮🇱' },
  { code: 'IM', name: 'Ilha de Man', flag: '🇮🇲' },
  { code: 'IN', name: 'Índia', flag: '🇮🇳' },
  { code: 'IO', name: 'Território Britânico do Oceano Índico', flag: '🇮🇴' },
  { code: 'IQ', name: 'Iraque', flag: '🇮🇶' },
  { code: 'IR', name: 'Irã', flag: '🇮🇷' },
  { code: 'IS', name: 'Islândia', flag: '🇮🇸' },
  { code: 'IT', name: 'Itália', flag: '🇮🇹' },
  { code: 'JE', name: 'Jersey', flag: '🇯🇪' },
  { code: 'JM', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'JO', name: 'Jordânia', flag: '🇯🇴' },
  { code: 'JP', name: 'Japão', flag: '🇯🇵' },
  { code: 'KE', name: 'Quênia', flag: '🇰🇪' },
  { code: 'KG', name: 'Quirguistão', flag: '🇰🇬' },
  { code: 'KH', name: 'Camboja', flag: '🇰🇭' },
  { code: 'KI', name: 'Kiribati', flag: '🇰🇮' },
  { code: 'KM', name: 'Comores', flag: '🇰🇲' },
  { code: 'KN', name: 'São Cristóvão e Nevis', flag: '🇰🇳' },
  { code: 'KP', name: 'Coreia do Norte', flag: '🇰🇵' },
  { code: 'KR', name: 'Coreia do Sul', flag: '🇰🇷' },
  { code: 'KW', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'KY', name: 'Ilhas Cayman', flag: '🇰🇾' },
  { code: 'KZ', name: 'Cazaquistão', flag: '🇰🇿' },
  { code: 'LA', name: 'Laos', flag: '🇱🇦' },
  { code: 'LB', name: 'Líbano', flag: '🇱🇧' },
  { code: 'LC', name: 'Santa Lúcia', flag: '🇱🇨' },
  { code: 'LI', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LK', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'LR', name: 'Libéria', flag: '🇱🇷' },
  { code: 'LS', name: 'Lesoto', flag: '🇱🇸' },
  { code: 'LT', name: 'Lituânia', flag: '🇱🇹' },
  { code: 'LU', name: 'Luxemburgo', flag: '🇱🇺' },
  { code: 'LV', name: 'Letônia', flag: '🇱🇻' },
  { code: 'LY', name: 'Líbia', flag: '🇱🇾' },
  { code: 'MA', name: 'Marrocos', flag: '🇲🇦' },
  { code: 'MC', name: 'Mônaco', flag: '🇲🇨' },
  { code: 'MD', name: 'Moldávia', flag: '🇲🇩' },
  { code: 'ME', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'MF', name: 'São Martinho', flag: '🇲🇫' },
  { code: 'MG', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'MH', name: 'Ilhas Marshall', flag: '🇲🇭' },
  { code: 'MK', name: 'Macedônia do Norte', flag: '🇲🇰' },
  { code: 'ML', name: 'Mali', flag: '🇲🇱' },
  { code: 'MM', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'MN', name: 'Mongólia', flag: '🇲🇳' },
  { code: 'MO', name: 'Macau', flag: '🇲🇴' },
  { code: 'MP', name: 'Ilhas Marianas do Norte', flag: '🇲🇵' },
  { code: 'MQ', name: 'Martinica', flag: '🇲🇶' },
  { code: 'MR', name: 'Mauritânia', flag: '🇲🇷' },
  { code: 'MS', name: 'Montserrat', flag: '🇲🇸' },
  { code: 'MT', name: 'Malta', flag: '🇲🇹' },
  { code: 'MU', name: 'Maurício', flag: '🇲🇺' },
  { code: 'MV', name: 'Maldivas', flag: '🇲🇻' },
  { code: 'MW', name: 'Malawi', flag: '🇲🇼' },
  { code: 'MX', name: 'México', flag: '🇲🇽' },
  { code: 'MY', name: 'Malásia', flag: '🇲🇾' },
  { code: 'MZ', name: 'Moçambique', flag: '🇲🇿' },
  { code: 'NA', name: 'Namíbia', flag: '🇳🇦' },
  { code: 'NC', name: 'Nova Caledônia', flag: '🇳🇨' },
  { code: 'NE', name: 'Níger', flag: '🇳🇪' },
  { code: 'NF', name: 'Ilha Norfolk', flag: '🇳🇫' },
  { code: 'NG', name: 'Nigéria', flag: '🇳🇬' },
  { code: 'NI', name: 'Nicarágua', flag: '🇳🇮' },
  { code: 'NL', name: 'Países Baixos', flag: '🇳🇱' },
  { code: 'NO', name: 'Noruega', flag: '🇳🇴' },
  { code: 'NP', name: 'Nepal', flag: '🇳🇵' },
  { code: 'NR', name: 'Nauru', flag: '🇳🇷' },
  { code: 'NU', name: 'Niue', flag: '🇳🇺' },
  { code: 'NZ', name: 'Nova Zelândia', flag: '🇳🇿' },
  { code: 'OM', name: 'Omã', flag: '🇴🇲' },
  { code: 'PA', name: 'Panamá', flag: '🇵🇦' },
  { code: 'PE', name: 'Peru', flag: '🇵🇪' },
  { code: 'PF', name: 'Polinésia Francesa', flag: '🇵🇫' },
  { code: 'PG', name: 'Papua-Nova Guiné', flag: '🇵🇬' },
  { code: 'PH', name: 'Filipinas', flag: '🇵🇭' },
  { code: 'PK', name: 'Paquistão', flag: '🇵🇰' },
  { code: 'PL', name: 'Polônia', flag: '🇵🇱' },
  { code: 'PM', name: 'São Pedro e Miquelon', flag: '🇵🇲' },
  { code: 'PN', name: 'Ilhas Pitcairn', flag: '🇵🇳' },
  { code: 'PR', name: 'Porto Rico', flag: '🇵🇷' },
  { code: 'PS', name: 'Palestina', flag: '🇵🇸' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹' },
  { code: 'PW', name: 'Palau', flag: '🇵🇼' },
  { code: 'PY', name: 'Paraguai', flag: '🇵🇾' },
  { code: 'QA', name: 'Catar', flag: '🇶🇦' },
  { code: 'RE', name: 'Reunião', flag: '🇷🇪' },
  { code: 'RO', name: 'Romênia', flag: '🇷🇴' },
  { code: 'RS', name: 'Sérvia', flag: '🇷🇸' },
  { code: 'RU', name: 'Rússia', flag: '🇷🇺' },
  { code: 'RW', name: 'Ruanda', flag: '🇷🇼' },
  { code: 'SA', name: 'Arábia Saudita', flag: '🇸🇦' },
  { code: 'SB', name: 'Ilhas Salomão', flag: '🇸🇧' },
  { code: 'SC', name: 'Seicheles', flag: '🇸🇨' },
  { code: 'SD', name: 'Sudão', flag: '🇸🇩' },
  { code: 'SE', name: 'Suécia', flag: '🇸🇪' },
  { code: 'SG', name: 'Singapura', flag: '🇸🇬' },
  { code: 'SH', name: 'Santa Helena', flag: '🇸🇭' },
  { code: 'SI', name: 'Eslovênia', flag: '🇸🇮' },
  { code: 'SJ', name: 'Svalbard e Jan Mayen', flag: '🇸🇯' },
  { code: 'SK', name: 'Eslováquia', flag: '🇸🇰' },
  { code: 'SL', name: 'Serra Leoa', flag: '🇸🇱' },
  { code: 'SM', name: 'San Marino', flag: '🇸🇲' },
  { code: 'SN', name: 'Senegal', flag: '🇸🇳' },
  { code: 'SO', name: 'Somália', flag: '🇸🇴' },
  { code: 'SR', name: 'Suriname', flag: '🇸🇷' },
  { code: 'SS', name: 'Sudão do Sul', flag: '🇸🇸' },
  { code: 'ST', name: 'São Tomé e Príncipe', flag: '🇸🇹' },
  { code: 'SV', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'SX', name: 'Sint Maarten', flag: '🇸🇽' },
  { code: 'SY', name: 'Síria', flag: '🇸🇾' },
  { code: 'SZ', name: 'Eswatini', flag: '🇸🇿' },
  { code: 'TC', name: 'Ilhas Turks e Caicos', flag: '🇹🇨' },
  { code: 'TD', name: 'Chade', flag: '🇹🇩' },
  { code: 'TF', name: 'Territórios Franceses do Sul', flag: '🇹🇫' },
  { code: 'TG', name: 'Togo', flag: '🇹🇬' },
  { code: 'TH', name: 'Tailândia', flag: '🇹🇭' },
  { code: 'TJ', name: 'Tajiquistão', flag: '🇹🇯' },
  { code: 'TK', name: 'Tokelau', flag: '🇹🇰' },
  { code: 'TL', name: 'Timor-Leste', flag: '🇹🇱' },
  { code: 'TM', name: 'Turcomenistão', flag: '🇹🇲' },
  { code: 'TN', name: 'Tunísia', flag: '🇹🇳' },
  { code: 'TO', name: 'Tonga', flag: '🇹🇴' },
  { code: 'TR', name: 'Turquia', flag: '🇹🇷' },
  { code: 'TT', name: 'Trinidad e Tobago', flag: '🇹🇹' },
  { code: 'TV', name: 'Tuvalu', flag: '🇹🇻' },
  { code: 'TW', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'TZ', name: 'Tanzânia', flag: '🇹🇿' },
  { code: 'UA', name: 'Ucrânia', flag: '🇺🇦' },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬' },
  { code: 'UM', name: 'Ilhas Menores Distantes dos Estados Unidos', flag: '🇺🇲' },
  { code: 'US', name: 'Estados Unidos', flag: '🇺🇸' },
  { code: 'UY', name: 'Uruguai', flag: '🇺🇾' },
  { code: 'UZ', name: 'Uzbequistão', flag: '🇺🇿' },
  { code: 'VA', name: 'Vaticano', flag: '🇻🇦' },
  { code: 'VC', name: 'São Vicente e Granadinas', flag: '🇻🇨' },
  { code: 'VE', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'VG', name: 'Ilhas Virgens Britânicas', flag: '🇻🇬' },
  { code: 'VI', name: 'Ilhas Virgens Americanas', flag: '🇻🇮' },
  { code: 'VN', name: 'Vietnã', flag: '🇻🇳' },
  { code: 'VU', name: 'Vanuatu', flag: '🇻🇺' },
  { code: 'WF', name: 'Wallis e Futuna', flag: '🇼🇫' },
  { code: 'WS', name: 'Samoa', flag: '🇼🇸' },
  { code: 'YE', name: 'Iêmen', flag: '🇾🇪' },
  { code: 'YT', name: 'Mayotte', flag: '🇾🇹' },
  { code: 'ZA', name: 'África do Sul', flag: '🇿🇦' },
  { code: 'ZM', name: 'Zâmbia', flag: '🇿🇲' },
  { code: 'ZW', name: 'Zimbábue', flag: '🇿🇼' }
];

export const getCountryByCode = (code: string): Country | undefined => {
  return COUNTRIES.find(country => country.code === code.toUpperCase());
};

export const getCountryFlag = (code: string): string => {
  const country = getCountryByCode(code);
  return country ? country.flag : '🏳️';
};